#!/usr/bin/env zsh

ensure_arch_package() {
  local name="$1"

  result="$(pacman -Q "${name}" 2&> /dev/null)"
  if [ $? -eq 1 ]; then
    log_info "Package not installed:" "${name}"
    ${DOTFILES_DRY_RUN} sudo pacman -S "${name}"
  fi
}
